accent = "#005FB8"
cursor = "#000000"
foreground = "#3B3B3B"
background = "#FFFFFF"
selection_foreground = "#FFFFFF"
selection_background = "#ADD6FF"
comment = "#008000"

color0 = "#000000"
color1 = "#CD3131"
color2 = "#107C10"
color3 = "#949800"
color4 = "#0451A5"
color5 = "#BC05BC"
color6 = "#0598BC"
color7 = "#555555"
color8 = "#666666"
color9 = "#CD3131"
color10 = "#14CE14"
color11 = "#B5BA00"
color12 = "#0451A5"
color13 = "#BC05BC"
color14 = "#0598BC"
color15 = "#A5A5A5"
